title = "Alpaca Sample Driver (Rotator)"

[network]
ip_address = '127.0.0.1'             # Any address
port = 5555

[server]
location = 'Anywhere on Earth'  # Anything you want here
verbose_driver_exceptions = true

[device]
can_reverse = true
step_size = 1.0
steps_per_sec = 6

[logging]
log_level = 'INFO'
log_to_stdout = false
max_size_mb = 5
num_keep_logs = 10

[[dwarfs]]
name = "DWARF II"
ip_address = "192.168.178.56"
device_num = 1

